name: Rust CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Clean Cargo registry cache
        run: rm -rf ~/.cargo/registry

      - name: Run tests
        run: cargo test
